error-exit if FILE is not found and/or "od" failed
Previously, because by default a pipe exits with the last command exit
code, errors in `cat' or `od' were not detected, resulting in empty
output and success exit (though typically with a message to stderr).

Now we error on such cases using custom pipefail-like behavior. Only
success/failure are detected (not propagating the actual error code).

We don't bother with native pipefail where possible, even if the POSIX
202X draft specifies it, because it requires more code to support both,
and additional subshell to detect. Our solution is small and good
enough, especially for an unimportant utility like shlolcat.

diff --git a/shlolcat b/shlolcat
--- a/shlolcat
+++ b/shlolcat
@@ -78,18 +78,23 @@ color_cycle() {
     esac
 }
 
-# main
-cat -- "$@" | list_as_octals | {
+# main, pipefail-like: if `cat' succeeds then 0 byte is appended to its output,
+# else 'x' is appended, and the code checks the last byte to detect errors.
+# if `od' failed (assuming no output) then we also exit with an error.
+# We don't bother with the actual error codes, nor testing for native pipefail.
+
+{ cat -- "$@" && printf \\0 || printf x; } | list_as_octals | {
     r=$max g=$min b=$min s=G+
     [ "$off" ] || { rand 100; off=$rnd; }  # 100x16 is full cycle with -a0 -b255
     while [ $off -gt 0 ]; do color_cycle 16; off=$((off-1)); done
 
     R=$r G=$g B=$b S=$s  # saved for next line
     x=0 e=0 line=  # column for tab tracking, esc state, line buffer
+    c= o=  # cur/prev octal. handling is delayed-by-1, last octal isn't printed
 
     trap 'printf \\033[0m' 2 3 6
     while read octals; do
-      for o in $octals; do
+      for c in $octals; do
         case $e$o in
         0033)  # esc
             [ "$esc" = no ] || line=$line\\$o
@@ -128,7 +133,9 @@ cat -- "$@" | list_as_octals | {
             case $o in 1??) e=0; esac
             ;;
         esac
+        o=$c  # current octal is handled at the next iteration, or below if EOF
       done
     done
     printf "$line\033[0m"
+    [ 000 = "$o" ] || err_exit  # last is 000 if cat succeeded + od translated
 }
