refine error handling
- more informative and unified error on out-of-range option value.
- trap (and reset color) only on SIGINT/SIGTERM, and exit with 128+sig.
- if od fails - exit with that code (previously we used 1).
- short usage displayed only on bad options or if od exit is <=127.

diff --git a/shlolcat b/shlolcat
--- a/shlolcat
+++ b/shlolcat
@@ -25,33 +25,35 @@ usage() {
 }
 
 err_exit() {
-    [ -z "${1-}" ] || >&2 echo "Error: $1"
-    >&2 echo "Usage: shlolcat -h | [-ea:b:c:x:y:o:] [FILE]..."
-    exit 1
+    [ "${1-}" ] && >&2 printf "%s: %s\n" "${0##*/}" "$1"
+    [ "${2-}" ] && >&2 printf "Usage: %s [-$opts] [FILE]...\n" "${0##*/}"
+    exit ${3:-1}
 }
 
-# true if $1 is an integer and $2 <= $1 <= $3
-intrange() {
-    case $1 in *[!0123456789]*|'') return 1; esac
-    [ "$1" -ge "$2" ] && [ "$1" -le "$3" ];
+intopt() {  # $1:opt-letter, $2:value, $3:target-var, $4:min, $5:max
+    case x${2#-} in x*[!0123456789]*|x) false; esac \
+    && [ "${#2}" -le 9 ] && [ "$2" -ge "$4" ] && [ "$2" -le "$5" ] \
+    && eval $3=\$2 || err_exit "illegal value: -$1 $2  ($4..$5)"
 }
 
-while getopts a:b:c:eho:x:y: o; do
+opts=a:b:c:eho:x:y:
+while getopts $opts o; do
     case $o in
         h) usage; exit 0;;
         e) esc=no;;
         c) case $OPTARG in 1|8|2|256|t|true) colors=$OPTARG;; *) err_exit "bad COLORS"; esac;;
-        o) intrange "$OPTARG" 0 100 && off=$OPTARG || err_exit "bad OFFSET";;
-        a) intrange "$OPTARG" 0 255 && min=$OPTARG ab=1 || err_exit "bad MIN";;
-        b) intrange "$OPTARG" 0 255 && max=$OPTARG ab=1 || err_exit "bad MAX";;
-        x) intrange "$OPTARG" 0 255 && dx=$OPTARG || err_exit "bad DX";;
-        y) intrange "$OPTARG" 0 255 && dy=$OPTARG || err_exit "bad DY";;
-        *) err_exit;;
+        o) intopt "$o" "$OPTARG" off 0 100;;
+        a) intopt "$o" "$OPTARG" min 0 255; ab=1;;
+        b) intopt "$o" "$OPTARG" max 0 255; ab=1;;
+        x) intopt "$o" "$OPTARG" dx 0 255;;
+        y) intopt "$o" "$OPTARG" dy 0 255;;
+        *) err_exit "" x;;
     esac
 done
+shift $((OPTIND-1))
+
 [ $min -le $max ] || err_exit "MIN is bigger than MAX"
 case $colors in 1|8) [ "$ab" ] || min=0 max=255; esac  # set full range if unset
-shift $((OPTIND-1))
 
 # list_as_octals prints input bytes as 3-digits octal values, several per line
 list_as_octals() { od -b -v -A n "$@"; }
@@ -90,7 +92,8 @@ color_cycle() {
     R=$r G=$g B=$b S=$s  # saved for next line
     x=0 e=0 line=  # column for tab tracking, esc state, line buffer
 
-    trap 'printf \\033[0m' 2 3 6
+    for sig in 2 15; do trap 'printf \\033[0m; exit '$((128+sig)) $sig; done
+
     while read octals; do
       for o in $octals; do
         case $e$o in
@@ -135,5 +138,6 @@ color_cycle() {
     done
 
     printf "$line\033[0m"
-    [ 0 = $octals ] || err_exit  # last is 0 if od suceesed
+    e=$octals  # last read is od exit code. print usage if e<128 (not signal)
+    [ $e -gt 127 ] && exit $e || [ $e = 0 ] || err_exit "" x $e
 }
